"""
BLF Pronominal Paradigms Engine.

Provides complete, deterministic declension matrices for personal, demonstrative,
interrogative, and relative pronouns across person, honorificity, and case dimensions.
"""

from typing import Any, Dict, List, Optional


class PronominalParadigmEngine:
    """Provides canonical pronominal declension tables for BDSB."""

    PRONOMINAL_MATRIX: Dict[str, Dict[str, str]] = {
        "PRON-1-SG": {
            "lemma": "আমি",
            "person": "1",
            "number": "SG",
            "honorific": "NEUTRAL",
            "NOM": "আমি",
            "ACC": "আমাকে",
            "GEN": "আমার",
            "LOC": "আমাতে",
        },
        "PRON-1-PL": {
            "lemma": "আমরা",
            "person": "1",
            "number": "PL",
            "honorific": "NEUTRAL",
            "NOM": "আমরা",
            "ACC": "আমাদেরকে",
            "GEN": "আমাদের",
            "LOC": "আমাদেরতে",
        },
        "PRON-2-HON-SG": {
            "lemma": "আপনি",
            "person": "2",
            "number": "SG",
            "honorific": "HONORIFIC",
            "NOM": "আপনি",
            "ACC": "আপনাকে",
            "GEN": "আপনার",
            "LOC": "আপনাতে",
        },
        "PRON-2-HON-PL": {
            "lemma": "আপনারা",
            "person": "2",
            "number": "PL",
            "honorific": "HONORIFIC",
            "NOM": "আপনারা",
            "ACC": "আপনাদেরকে",
            "GEN": "আপনাদের",
            "LOC": "আপনাদেরতে",
        },
        "PRON-2-FAM-SG": {
            "lemma": "তুমি",
            "person": "2",
            "number": "SG",
            "honorific": "FAMILIAR",
            "NOM": "তুমি",
            "ACC": "তোমাকে",
            "GEN": "তোমার",
            "LOC": "তোমাতে",
        },
        "PRON-2-FAM-PL": {
            "lemma": "তোমরা",
            "person": "2",
            "number": "PL",
            "honorific": "FAMILIAR",
            "NOM": "তোমরা",
            "ACC": "তোমাদেরকে",
            "GEN": "তোমাদের",
            "LOC": "তোমাদেরতে",
        },
        "PRON-2-INT-SG": {
            "lemma": "তুই",
            "person": "2",
            "number": "SG",
            "honorific": "INTIMATE",
            "NOM": "তুই",
            "ACC": "তোকে",
            "GEN": "তোর",
            "LOC": "তোতে",
        },
        "PRON-2-INT-PL": {
            "lemma": "তোরা",
            "person": "2",
            "number": "PL",
            "honorific": "INTIMATE",
            "NOM": "তোরা",
            "ACC": "তোদেরকে",
            "GEN": "তোদের",
            "LOC": "তোদেরতে",
        },
        "PRON-3-PROX-ORD-SG": {
            "lemma": "এ",
            "person": "3",
            "number": "SG",
            "honorific": "ORDINARY",
            "deixis": "PROXIMAL",
            "NOM": "এ",
            "ACC": "একে",
            "GEN": "এর",
            "LOC": "এতে",
        },
        "PRON-3-PROX-ORD-PL": {
            "lemma": "এরা",
            "person": "3",
            "number": "PL",
            "honorific": "ORDINARY",
            "deixis": "PROXIMAL",
            "NOM": "এরা",
            "ACC": "এদেরকে",
            "GEN": "এদের",
            "LOC": "এদেরতে",
        },
        "PRON-3-PROX-HON-SG": {
            "lemma": "ইনি",
            "person": "3",
            "number": "SG",
            "honorific": "HONORIFIC",
            "deixis": "PROXIMAL",
            "NOM": "ইনি",
            "ACC": "এঁকে",
            "GEN": "এঁর",
            "LOC": "এঁতে",
        },
        "PRON-3-MED-ORD-SG": {
            "lemma": "ও",
            "person": "3",
            "number": "SG",
            "honorific": "ORDINARY",
            "deixis": "MEDIAL",
            "NOM": "ও",
            "ACC": "ওকে",
            "GEN": "ওর",
            "LOC": "ওতে",
        },
        "PRON-3-MED-HON-SG": {
            "lemma": "উনি",
            "person": "3",
            "number": "SG",
            "honorific": "HONORIFIC",
            "deixis": "MEDIAL",
            "NOM": "উনি",
            "ACC": "ওঁকে",
            "GEN": "ওঁর",
            "LOC": "ওঁতে",
        },
        "PRON-3-DIST-ORD-SG": {
            "lemma": "সে",
            "person": "3",
            "number": "SG",
            "honorific": "ORDINARY",
            "deixis": "DISTAL",
            "NOM": "সে",
            "ACC": "তাকে",
            "GEN": "তার",
            "LOC": "তাতে",
        },
        "PRON-3-DIST-ORD-PL": {
            "lemma": "তারা",
            "person": "3",
            "number": "PL",
            "honorific": "ORDINARY",
            "deixis": "DISTAL",
            "NOM": "তারা",
            "ACC": "তাদেরকে",
            "GEN": "তাদের",
            "LOC": "তাদেরতে",
        },
        "PRON-3-DIST-HON-SG": {
            "lemma": "তিনি",
            "person": "3",
            "number": "SG",
            "honorific": "HONORIFIC",
            "deixis": "DISTAL",
            "NOM": "তিনি",
            "ACC": "তাঁকে",
            "GEN": "তাঁর",
            "LOC": "তাঁতে",
        },
        "PRON-3-DIST-HON-PL": {
            "lemma": "তাঁরা",
            "person": "3",
            "number": "PL",
            "honorific": "HONORIFIC",
            "deixis": "DISTAL",
            "NOM": "তাঁরা",
            "ACC": "তাঁদেরকে",
            "GEN": "তাঁদের",
            "LOC": "তাঁদেরতে",
        },
        "PRON-INTERROGATIVE-HUMAN-SG": {
            "lemma": "কে",
            "person": "3",
            "number": "SG",
            "honorific": "NEUTRAL",
            "type": "INTERROGATIVE",
            "NOM": "কে",
            "ACC": "কাকে",
            "GEN": "কার",
            "LOC": "কাতে",
        },
        "PRON-INTERROGATIVE-HUMAN-PL": {
            "lemma": "কারা",
            "person": "3",
            "number": "PL",
            "honorific": "NEUTRAL",
            "type": "INTERROGATIVE",
            "NOM": "কারা",
            "ACC": "কাদেরকে",
            "GEN": "কাদের",
            "LOC": "কাদেরতে",
        },
        "PRON-RELATIVE-HUMAN-SG": {
            "lemma": "যে",
            "person": "3",
            "number": "SG",
            "honorific": "NEUTRAL",
            "type": "RELATIVE",
            "NOM": "যে",
            "ACC": "যাকে",
            "GEN": "যার",
            "LOC": "যাতে",
        },
        "PRON-RELATIVE-HUMAN-PL": {
            "lemma": "যারা",
            "person": "3",
            "number": "PL",
            "honorific": "NEUTRAL",
            "type": "RELATIVE",
            "NOM": "যারা",
            "ACC": "যাদেরকে",
            "GEN": "যাদের",
            "LOC": "যাদেরতে",
        },
    }

    def get_pronominal_paradigm(self, pronoun_id: str) -> Optional[Dict[str, str]]:
        return self.PRONOMINAL_MATRIX.get(pronoun_id)

    def get_all_paradigms(self) -> Dict[str, Dict[str, str]]:
        return self.PRONOMINAL_MATRIX
